hotkeys:
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  new-tab:
    - Ctrl-Shift-T
  toggle-window:
    - Ctrl-Space
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
  restart-telnet-session: []
  serial:
    - Alt-K
  restart-serial-session: []
terminal:
  frontend: xterm
  fontSize: 14
  fontWeight: 400
  fontWeightBold: 700
  fallbackFont: null
  linePadding: 0
  bell: 'off'
  bracketedPaste: true
  background: theme
  ligatures: true
  cursorBlink: true
  rightClick: clipboard
  pasteOnMiddleClick: false
  copyOnSelect: true
  copyAsHTML: true
  scrollOnInput: true
  altIsMeta: false
  wordSeparator: ' ()[]{}''"'
  colorScheme:
    name: Rose Pine
    foreground: '#e0def4'
    background: '#191724'
    cursor: '#555169'
    colors:
      - '#26233a'
      - '#eb6f92'
      - '#31748f'
      - '#f6c177'
      - '#9ccfd8'
      - '#c4a7e7'
      - '#ebbcba'
      - '#e0def4'
      - '#6e6a86'
      - '#eb6f92'
      - '#31748f'
      - '#f6c177'
      - '#9ccfd8'
      - '#c4a7e7'
      - '#ebbcba'
      - '#e0def4'
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  customColorSchemes: []
  warnOnMultilinePaste: false
  searchRegexAlwaysEnabled: false
  searchOptions: {}
  detectProgress: true
  scrollbackLines: 25000
  drawBoldTextInBrightColors: true
  sixel: true
  minimumContrastRatio: 4
  trimWhitespaceOnPaste: true
  font: Consolas
  useConPTY: false
  environment: {}
  setComSpec: false
  profile: local:clink
  showBuiltinProfiles: true
  showRecentProfiles: 3
  paneResizeStep: 0.1
  focusFollowsMouse: false
  identification: wt
  hideTabOptionsButton: true
ssh:
  warnOnClose: true
  winSCPPath: null
  agentType: auto
  agentPath: null
  x11Display: null
  knownHosts: []
  verifyHostKeys: false
configSync:
  configID: null
  auto: false
  parts:
    hotkeys: true
    appearance: true
    vault: true
clickableLinks:
  modifier: null
accessibility:
  animations: true
appearance:
  dockScreen: current
  dockFill: 0.5
  dockSpace: 1
  dockHideOnBlur: false
  dockAlwaysOnTop: true
  tabsLocation: top
  tabsInFullscreen: false
  cycleTabs: true
  theme: Follow the color scheme
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 0.89
  vibrancy: false
  vibrancyType: blur
  spaciness: 1
  colorSchemeMode: dark
profiles: []
groups: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
enableAnalytics: false
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
version: 7
vault: null
encrypted: false
enableExperimentalFeatures: false
commandBlacklist: []
providerBlacklist: []
profileBlacklist: []
hacks:
  disableGPU: false
  disableVibrancyWhileDragging: false
  enableFluentBackground: false
language: null
defaultQuickConnectProvider: ssh
highlightPlugin:
  highlightProfiles:
    - id: 60606be0-c0ff-42bc-bf77-de8a2435447f
      name: Default
      keywords:
        - text: ERROR
          enabled: true
          background: true
          backgroundColor: '1'
        - text: WARN
          enabled: true
          background: true
          backgroundColor: '3'
        - text: INFO
          enabled: true
          background: true
          backgroundColor: '6'
        - text: 错误
          enabled: true
          background: true
          backgroundColor: '1'
        - text: 警告
          enabled: true
          background: true
          backgroundColor: '3'
        - text: 信息
          enabled: true
          background: true
          backgroundColor: '6'
  replaceProfiles:
    - id: 986666dd-dac9-4c7a-a295-9b4aff66abdd
      name: Default
      patterns:
        - enabled: true
          search: ERROR
          replace: 出错啦
        - enabled: true
          search: WARN
          replace: 警告警告
pluginBlacklist: []
