"use strict";
module.exports = {
    config: {
        updateChannel: 'stable',
        fontSize: 14,
        fontFamily: '"JetBrainsMono", Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',
        fontWeight: 'normal',
        fontWeightBold: 'bold',
        lineHeight: 1,
        letterSpacing: 0,
        cursorColor: 'rgba(55, 11, 201)',
        cursorAccentColor: '#000',
        cursorShape: 'BLOCK',
        cursorBlink: true,
        foregroundColor: '#fff',
        backgroundColor: '#000',
        selectionColor: 'rgba(248,28,229,0.3)',
        borderColor: '#333',
        css: '',
        termCSS: '',
        workingDirectory: 'C:\\Users\\Admin\\Desktop\\Scripting\\Current',
        showHamburgerMenu: true,
        showWindowControls: '',
        padding: '12px 14px',
        colors: {
            black: '#000000',
            red: '#C51E14',
            green: '#1DC121',
            yellow: '#C7C329',
            blue: '#0A2FC4',
            magenta: '#C839C5',
            cyan: '#20C5C6',
            white: '#C7C7C7',
            lightBlack: '#686868',
            lightRed: '#FD6F6B',
            lightGreen: '#67F86F',
            lightYellow: '#FFFA72',
            lightBlue: '#6A76FB',
            lightMagenta: '#FD7CFC',
            lightCyan: '#68FDFE',
            lightWhite: '#FFFFFF',
            limeGreen: '#32CD32',
            lightCoral: '#F08080',
        },
        shell: 'powershell.exe',
        shellArgs: [],
        env: {},
        bell: 'SOUND',
        copyOnSelect: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: false,
        webLinksActivationKey: '',
        disableLigatures: false,
        disableAutoUpdates: false,
        screenReaderMode: false,
        preserveCWD: true,
        opacity: 0.80,

        //catppuccinTheme: 'mocha',
    },
    plugins: [
        "hyper-alt-click",
        "hyper-opacity",
        "hyper-manager",
        "hyper-hide-scroll",
        "hyper-tabs-enhanced",
        "hyper-rose-pine",
        //"hypurr"
    ],
    localPlugins: [],
    keymaps: {
    },
    
};
