watch_stylesheet: true
watch_config: true
debug: false
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 300
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: "#cba6f7"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 38
    padding:
      top: 4
      left: 8
      bottom: 4
      right: 8
    widgets:
      left:
        [
          "home",
          "media",
          "active_window"
        ]
      center:
        [
          clock,
          weather
        ]
      right:
        [
          "cava",
          "cpu",
          "memory",
          "battery",
          "power_menu"
        ]
widgets:
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 18
      min_bar_height: 2
      gradient: 1
      foreground: "#cba6f7"
      gradient_color_1: '#cba6f7'
      gradient_color_2: '#89b4fa'
      bars_number: 20
      bar_spacing: 2
      bar_width: 3
      bar_type: "bars"
      noise_reduction: 0.10
      edge_fade: 35
      sleep_timer: 0
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | {time_remaining}"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 800
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      label_shadow:
        enabled: true
        color: "black"
        radius: 4
        offset: [ 1, 1 ]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "C:\\Users\\camus\\Downloads"}
        - { title: "Documents", path: "C:\\Users\\camus\\Documents"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#cba6f7"
      distance: 8
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 12
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title} - {artist}"
      hide_empty: true
      callbacks:
       on_left: "toggle_media_menu"
       on_middle: "do_nothing"
       on_right: "toggle_label"
      max_field_size:
        label: 45
        label_alt: 45
      show_thumbnail: true
      controls_only: false
      controls_left: true
      thumbnail_alpha: 80
      thumbnail_padding: 4
      thumbnail_corner_radius: 12
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
       blur: true
       round_corners: true
       round_corners_type: "normal"
       border_color: "#cba6f7"
       alignment: "right"
       direction: "down"
       offset_top: 8
       offset_left: 0
       thumbnail_corner_radius: 12
       thumbnail_size: 140
       max_title_size: 80
       max_artist_size: 20
       show_source: true
      media_menu_icons:
       play: "\ue768"
       pause: "\ue769"
       prev_track: "\ue892"
       next_track: "\ue893"
      label_shadow:
       enabled: true
       color: "black"
       radius: 4
       offset: [ 1, 1 ]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 12
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b - %I:%M}"
      label_alt: "{%a, %d %b %H:%M:%S}"
      timezones: []
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 8
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp} - {location}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: 'ae56bdf6ff904f0ab4a220654250210'
      update_interval: 600
      hide_decimal: true
      location: "Portland, ME, USA"
      units: "imperial"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyIcyDay: "\udb81\udf17"
        snowyIcyNight: "\udb81\udf17"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#cba6f7"
        alignment: "right"
        direction: "down"
        distance: 8
        icon_size: 56
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 12
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: True
      blur_background: True
      animation_duration: 300
      button_row: 3
      buttons:
        lock: ["\uf023","Lock"]
        signout: ["\udb80\udf43","Sign out"]
        sleep: ["\udb82\udd04","Sleep"]
        restart: ["\uead2","Restart"]
        shutdown: ["\uf011","Shut Down"]
        cancel: ["\udb81\udf3a","Cancel"]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: ""
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581'
        - '\u2581'
        - '\u2582'
        - '\u2583'
        - '\u2584'
        - '\u2585'
        - '\u2586'
        - '\u2587'
        - '\u2588'
      histogram_num_columns: 10
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8